### PR TITLE
Add luganda sentences

### PR DESCRIPTION
**Pull request by jmukiibi**
Added 2nd batch of 5000 CC0 Luganda sentences validated and verified.

### CODE REVIEW

**Comment by phirework** [comment]
Hi, for this and #2966, can you explain what the source of the sentences are and how you went about validating them?

**Comment by jmukiibi** [comment]
The sentences we created and generated by the community members. These were validated by Linguists for grammatical errors, spellings and biases like race and others.

**Comment by jmukiibi** [comment]
@phirework can you please look into my PR. Thanks

**Comment by phirework** [comment]
Do you mean that the sentences were written by community members? How were you doing the validation? Through the sentence collector, or something else? 

Normally when we receive bulk texts from source that aren't the sentence collector, we ask for records of at least a sample of the validation, along with error rate of the sentences. See the documentation on [bulk importing](https://github.com/mozilla/common-voice/blob/main/docs/SENTENCES.md#bulk-submission) for more info. It doesn't have to be exactly in that format, as long as there's some form of documentation.

**Comment by jmukiibi** [comment]
@phirework Yes. Even our first batch was a bulk one. With the help of Mozilla, we have set up a community on the ground which includes text searchers, text creators, text validators, text mobilizers. This includes linguistics from the department of languages. We don't use sentence collector tool but rather we have our own version of [pontoon](https://airnlp.herokuapp.com/). We upload English sentences from text creators and translate them to Luganda. In the process of translating, these are reviewed and later downloaded.

**Pull request merged**
