### PR TITLE
Removed lines that just says a number.

### PR DESCRIPTION
**Pull request by Oymate**
Example:
Five
Six

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Why do you think those should be removed?

**Comment by Oymate** [comment]
@MichaelKohler I felt like these do not add much value in terms of language detection as numbers were discouraged initially. But if it is acceptable than this PR may be closed.  :)

**Comment by MichaelKohler** [comment]
Numbers are discouraged, but only if they are actual numbers like 1, 2, etc, absolutely fine if they are written out like "one", "two". Thanks though!

**Comment by Oymate** [comment]
@MichaelKohler Thanks for reviewing  :)

**Pull request closed without merging**
