### PR TITLE
Sentence Collector - Validated sentences export - 2020 - 11 - 29

### PR DESCRIPTION
**Pull request by rbaghdadi**

### CODE REVIEW

**Comment by MichaelKohler** [comment]
I'll have a look at this later today or tomorrow. In general: this export happens automatically every Friday. There might not be much benefit of merging this, if there isn't also a Common Voice deployment schedules between now and Friday.

**Review by MichaelKohler — APPROVED** [review]

**Comment by mozillakab** [comment]
@MichaelKohler  Please we need a new extraction. Kabyle queue is empty on CV

**Comment by MichaelKohler** [comment]
5 days ago 6900 new sentences were exported to the common voice repository. These will be part of the next deployment, can't say when that will be though (cc @phirework)

**Comment by mozillakab** [comment]
Thanks @MichaelKohler ,

**Pull request merged**
